let intenseSexualDares = [
  "Perform a striptease for me while maintaining eye contact.",
  "Touch yourself in front of me for 2 minutes while I watch.",
  "Give me a passionate kiss, then kiss me all the way down to my inner thighs.",
  "Tie my hands up and take full control of me for the next 5 minutes.",
  "Let me use my hands on you for 3 minutes without you making a sound.",
  "Tease me with your body but don’t let me touch you for 3 minutes.",
  "Slowly kiss every inch of my body, no skipping any parts.",
  "Give me a lap dance, but make sure not to stop until I say so.",
  "Kiss and lick me anywhere you want, but you can’t stop until I’m begging.",
  "Undress me using only your mouth.",
  "Let me watch as you slowly pleasure yourself.",
  "Pick one of my sensitive spots and tease it with your tongue for 2 minutes.",
  "Make me feel good using only your hands for 3 minutes—no stopping.",
  "Let me tie you up and tease you any way I want for 5 minutes.",
  "Kiss and touch me everywhere, but you can't let me finish for 5 minutes.",
  "Take control and show me exactly how you want to be pleased.",
  "Give me a full-body massage, but use only your mouth.",
  "Use your mouth to slowly undress me and kiss each exposed part.",
  "Pick a position and act out one of your fantasies with me.",
  "Kiss me passionately while your hands explore my body wherever you want.",
  "Tease me with your mouth, but don’t let me touch you for 2 minutes.",
  "Give me an intense kiss while touching me intimately for 3 minutes.",
  "Let me do anything I want to you for the next 5 minutes.",
  "Use your mouth to bring me as close to climax as possible without letting me finish.",
  "Whisper a fantasy you want to try while you touch yourself in front of me.",
  "Undress me slowly and kiss me in every place you uncover.",
  "Tease me with your fingers for 2 minutes without allowing me to touch you.",
  "Let me tie you up and explore your body for 5 minutes without you speaking.",
  "Take off your clothes and let me touch you wherever I want for 2 minutes.",
  "Use your hands and mouth on me for 3 minutes without letting me finish.",
  "Show me how you like to be touched while I watch closely.",
  "Kiss me deeply while your hands explore under my clothes.",
  "Tease me until I can’t take it anymore, then push me even further.",
  "Use your mouth to tease me, but you can’t let me finish for 5 minutes.",
  "Give me a lap dance, but you can’t let me touch you.",
  "Act out a roleplay scenario of your choice for 5 minutes.",
  "Show me your favorite position, then let me take control in it.",
  "Use your hands to explore every inch of my body while kissing me.",
  "Kiss me passionately while you undress both of us.",
  "Tease me with your mouth and hands for 3 minutes without letting me finish.",
  "Undress me using only your teeth, no hands allowed.",
  "Let me kiss and touch you anywhere, but you can’t let me finish for 5 minutes.",
  "Take full control and show me how you want to be pleased.",
  "Let me tie you up and tease you for 5 minutes while you stay still.",
  "Kiss me slowly while your hands work their way down my body.",
  "Make me watch as you pleasure yourself for 2 minutes.",
  "Take control of me and do whatever you want for the next 5 minutes.",
  "Kiss me intensely while your hands explore under my clothes.",
  "Use your mouth to tease me for 3 minutes without letting me finish.",
  "Let me tie you up and tease you for 5 minutes while you stay still.",
  "Kiss me passionately while your hands explore my most sensitive spots.",
  "Use your mouth to undress me, then kiss every part of my body.",
  "Take control of me and show me how you want to be touched.",
  "Use only your mouth to bring me as close to climax as possible.",
  "Make me watch as you slowly undress and tease yourself.",
  "Pick a fantasy and act it out with me for 5 minutes.",
  "Kiss and touch me intimately while making sure I can't finish for 5 minutes.",
  "Let me use my hands and mouth on you for 3 minutes.",
  "Whisper a dirty secret while you touch yourself in front of me.",
  "Tease me until I’m begging, then make me wait a little longer.",
  "Use your hands to explore my body, but you can't let me touch you.",
  "Act out your favorite sexual position with me.",
  "Show me how you want to be kissed and touched, then let me take control.",
  "Kiss me intensely, while you undress me slowly.",
  "Give me an intimate massage, but use only your mouth and hands.",
  "Tease me with your lips for 2 minutes without letting me finish.",
  "Take control and make me do whatever you want for 5 minutes.",
  "Undress me using your teeth and then kiss my body all over.",
  "Give me a lap dance while maintaining eye contact the entire time.",
  "Whisper your naughtiest fantasy while touching me.",
  "Use your mouth and hands to tease me for 3 minutes without letting me finish.",
  "Let me use my mouth on you for 2 minutes while you try not to make a sound.",
  "Kiss me slowly while your hands work their way down my body.",
  "Take control and show me how you like to be touched.",
  "Tease me with your hands for 3 minutes without letting me touch you.",
  "Act out a sexual roleplay scenario with me.",
  "Kiss and touch me anywhere you want, but don’t let me finish for 5 minutes.",
  "Take off your clothes and let me touch you wherever I want for 3 minutes.",
  "Give me a lap dance while keeping your hands behind your back.",
  "Tease me with your mouth for 3 minutes without letting me finish.",
  "Use your hands to explore my body while you kiss me passionately.",
  "Kiss me slowly while undressing both of us.",
  "Show me how you like to be touched, then take control.",
  "Take full control of me and do whatever you want for 5 minutes.",
  "Make me watch as you pleasure yourself for 2 minutes while I can't touch you.",
  "Use your hands and mouth to bring me as close to climax as possible without letting me finish.",
  "Tease me with your lips, but don’t let me touch you for 2 minutes.",
  "Whisper a dirty fantasy you want to try, then start acting it out with me.",
  "Kiss me passionately while undressing both of us.",
  "Tease me with your mouth and hands for 3 minutes without letting me finish."
];

// Function to get a random dare
function getRandomDare() {
    const randomIndex = Math.floor(Math.random() * intenseSexualDares.length);
    return intenseSexualDares[randomIndex];
}

// Event listener for button click
document.getElementById("dareButton").addEventListener("click", function() {
    const randomDare = getRandomDare();
    document.getElementById("dareDisplay").innerText = randomDare;
});
